### ISSUE TITLE
RuntimeError: cuda runtime error (59): device-side assert triggered

### ISSUE THREAD

**Issue by zzy-ucas** [chenxinpeng/ARNet#3]
When I try to run this project, after a few steps, I meet this error at line:
`output = torch.sum(output) / batch_size` in the 'image_caption_ende_xe.py'
the output is Variable of 'torch.cuda.FloatTensor' and the type of 'batch_size' is 'float'. But I do not know where is the problem. 
My environment: Pytorch-0.3.1 with python2.7.
Please Help! Thanks a lot!

**Comment by chenxinpeng** [comment]
@zzy-ucas 

Hi,
Thank you for reporting this issue.

As aforementioned in the [Introduction](https://github.com/chenxinpeng/ARNet/tree/master/image_captioning#dependencies), you should use  PyTorch 0.1.12.

If you want to use higher version of PyTorch, please generate the data, such as `train_images_captions_index.pkl` by your self.

**Comment by zzy-ucas** [comment]
Thanks for your reply. @chenxinpeng

Yes, I have generated this `train_images_captions_index.pkl`. But there may be something wrong with this file!
I find that the error location: `output = - input.gather(1, target) * mask` in the `utils_model.py`.
And my  vocab size is larger than 300. But `input.size(1)` is 288 constantly. This makes the index out of range.
·class LanguageModelCriterion(nn.Module):
    def __init__(self):
        super(LanguageModelCriterion, self).__init__()

    def forward(self, input, target, mask):
        batch_size = input.size(0)

        target = target[:, :input.size(1)]
        mask = mask[:, :input.size(1)]

        input = to_contiguous(input).view(-1, input.size(2))

        target = to_contiguous(target).view(-1, 1)
        mask = to_contiguous(mask).view(-1, 1)

        target_cpu = target.data.cpu().numpy()
        # Here input.size(1) is 288 fixed! But my vocab size is larger than 300. 
        output = - input.gather(1, target) * mask
        output = torch.sum(output) / batch_size

        return output·

·RuntimeError: Invalid index in gather at /pytorch/torch/lib/TH/generic/THTensorMath.c:535·

So, when the max number in the 'target' is larger than 288, it will stop running.

**Comment by zzy-ucas** [comment]
Thanks for your reply. @chenxinpeng

Yes, I have generated this 'train_images_captions_index.pkl'. But there may be something wrong with this file!
I find that the error location: 
'output = - input.gather(1, target) * mask' in the 'utils_model.py'.
And my vocab size is larger than 300. But input.size(1) is 288 constantly. This makes the index out of range.
·def forward(self, input, target, mask):
    batch_size = input.size(0)

    target = target[:, :input.size(1)]
    mask = mask[:, :input.size(1)]

    input = to_contiguous(input).view(-1, input.size(2))

    target = to_contiguous(target).view(-1, 1)
    mask = to_contiguous(mask).view(-1, 1)

    target_cpu = target.data.cpu().numpy()
    # Here input.size(1) is 288 fixed! But my vocab size is larger than 300. 
    output = - input.gather(1, target) * mask
    output = torch.sum(output) / batch_size

    return output·
·RuntimeError: Invalid index in gather at /pytorch/torch/lib/TH/generic/THTensorMath.c:535·

So, when the max number in the 'target' is larger than 288, it will stop running.

**Comment by zzy-ucas** [comment]
Thanks for your reply. @chenxinpeng

Yes, I have generated this 
'train_images_captions_index.pkl'. 
But there may be something wrong with this file!  find that the error location:
'output = - input.gather(1, target) * mask' in the 'utils_model.py'.
And my vocab size is larger than 300. But input.size(1) is 288 constantly. This makes the index out of range.


`def forward(self, input, target, mask):
batch_size = input.size(0)

target = target[:, :input.size(1)]
mask = mask[:, :input.size(1)]

input = to_contiguous(input).view(-1, input.size(2))

target = to_contiguous(target).view(-1, 1)
mask = to_contiguous(mask).view(-1, 1)

target_cpu = target.data.cpu().numpy()
# Here input.size(1) is 288 fixed! But my vocab size is larger than 300. 
output = - input.gather(1, target) * mask
output = torch.sum(output) / batch_size

return output`
`RuntimeError: Invalid index in gather at /pytorch/torch/lib/TH/generic/THTensorMath.c:535`

So, when the max number in the 'target' is larger than 288, it will stop running.

**Comment by zzy-ucas** [comment]
Thanks for your reply. @chenxinpeng

Yes, I have generated this 
'train_images_captions_index.pkl'. 
But there may be something wrong with this file!  find that the error location:
'output = - input.gather(1, target) * mask' in the 'utils_model.py'.
And my vocab size is larger than 300. But input.size(1) is 288 constantly. This makes the index out of range.


<def forward(self, input, target, mask):
batch_size = input.size(0)

target = target[:, :input.size(1)]
mask = mask[:, :input.size(1)]

input = to_contiguous(input).view(-1, input.size(2))

target = to_contiguous(target).view(-1, 1)
mask = to_contiguous(mask).view(-1, 1)

target_cpu = target.data.cpu().numpy()
### Here input.size(1) is 288 fixed! But my vocab size is larger than 300. 
output = - input.gather(1, target) * mask
output = torch.sum(output) / batch_size

return output>
`RuntimeError: Invalid index in gather at /pytorch/torch/lib/TH/generic/THTensorMath.c:535`

So, when the max number in the 'target' is larger than 288, it will stop running.

**Comment by zzy-ucas** [comment]
Thanks for your reply. @chenxinpeng

Yes, I have generated this 
'train_images_captions_index.pkl'. 
But there may be something wrong with this file!  find that the error location:
'output = - input.gather(1, target) * mask' in the 'utils_model.py'.
And my vocab size is larger than 300. But input.size(1) is 288 constantly. This makes the index out of range.

`
def forward(self, input, target, mask):
batch_size = input.size(0)

target = target[:, :input.size(1)]
mask = mask[:, :input.size(1)]

input = to_contiguous(input).view(-1, input.size(2))

target = to_contiguous(target).view(-1, 1)
mask = to_contiguous(mask).view(-1, 1)

target_cpu = target.data.cpu().numpy()
$$ Here input.size(1) is 288 fixed! But my vocab size is larger than 300. 
output = - input.gather(1, target) * mask
output = torch.sum(output) / batch_size

return output
`
`RuntimeError: Invalid index in gather at /pytorch/torch/lib/TH/generic/THTensorMath.c:535`

So, when the max number in the 'target' is larger than 288, it will stop running.

**Comment by zzy-ucas** [comment]
Thanks for your reply. @chenxinpeng

Yes, I have generated this
'train_images_captions_index.pkl'.
But there may be something wrong with this file! find that the error location:
'output = - input.gather(1, target) * mask' in the 'utils_model.py'.
And my vocab size is larger than 300. But input.size(1) is 288 constantly. This makes the index out of range.

`def forward(self, input, target, mask):
      batch_size = input.size(0)

      target = target[:, :input.size(1)]
      mask = mask[:, :input.size(1)]

      input = to_contiguous(input).view(-1, input.size(2))

      target = to_contiguous(target).view(-1, 1)
      mask = to_contiguous(mask).view(-1, 1)

      target_cpu = target.data.cpu().numpy()
      $$ Here input.size(1) is 288 fixed! But my vocab size is larger than 300.
      output = - input.gather(1, target) * mask
      output = torch.sum(output) / batch_size
return output`

`RuntimeError: Invalid index in gather at /pytorch/torch/lib/TH/generic/THTensorMath.c:535`

So, when the max number in the 'target' is larger than 288, it will stop running.

**Comment by zzy-ucas** [comment]
Thanks for your reply. @chenxinpeng

Yes, I have generated this
'train_images_captions_index.pkl'.
But there may be something wrong with this file! find that the error location:
'output = - input.gather(1, target) * mask' in the 'utils_model.py'.
And my vocab size is larger than 300. But input.size(1) is 288 constantly. This makes the index out of range.

"def forward(self, input, target, mask):
  batch_size = input.size(0)

  target = target[:, :input.size(1)]
  mask = mask[:, :input.size(1)]

  input = to_contiguous(input).view(-1, input.size(2))

  target = to_contiguous(target).view(-1, 1)
  mask = to_contiguous(mask).view(-1, 1)

  target_cpu = target.data.cpu().numpy()
  # Here input.size(1) is 288 fixed! But my vocab size is larger than 300.
  output = - input.gather(1, target) * mask
  output = torch.sum(output) / batch_size
return output"

`RuntimeError: Invalid index in gather at /pytorch/torch/lib/TH/generic/THTensorMath.c:535`

So, when the max number in the 'target' is larger than 288, it will stop running.

**Comment by zzy-ucas** [comment]
Thanks for your reply. @chenxinpeng

Yes, I have generated this
'train_images_captions_index.pkl'.
But there may be something wrong with this file! find that the error location:
'output = - input.gather(1, target) * mask' in the 'utils_model.py'.
And my vocab size is larger than 300. But input.size(1) is 288 constantly. This makes the index out of range.

`output = - input.gather(1, target) * mask`
`output = torch.sum(output) / batch_size`

`RuntimeError: Invalid index in gather at /pytorch/torch/lib/TH/generic/THTensorMath.c:535`

So, when the max number in the 'target' is larger than 288, it will stop running.

**Comment by zzy-ucas** [comment]
Thanks for your reply. @chenxinpeng

Yes, I have generated this
'train_images_captions_index.pkl'.
But there may be something wrong with this file!
'output = - input.gather(1, target) * mask' in the 'utils_model.py'.
My vocab size is 288 and the 'input.size(1)' is 288 constantly. 

`RuntimeError: Invalid index in gather at /pytorch/torch/lib/TH/generic/THTensorMath.c:535`

But the max number in the 'target' is 288 in some batch. It should be from 0 to 287. This makes the index out of range. And the project stops running. I still checking why it comes!

**Comment by zzy-ucas** [comment]
@chenxinpeng ehh... I have solved the problem! Sorry to bother you!

-Error: RuntimeError: cuda runtime error (59): device-side assert triggered.
-Solutions: check the target and it should be from 0 to n-1.(if n classes)

That's all! I am a github newbier here. So sorry to bother you! 
Closed!
